// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADueWHHk0xK26zHOHMTqXUZIpNJjvgO5A',
    appId: '1:848790076272:web:896e90aee6fbbfcb192db5',
    messagingSenderId: '848790076272',
    projectId: 'dollar-ac665',
    authDomain: 'dollar-ac665.firebaseapp.com',
    databaseURL: 'https://dollar-ac665-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dollar-ac665.firebasestorage.app',
    measurementId: 'G-L5E6P6V8ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmLW2Z04azlKulEr1_YPPDyCP65iH7wiw',
    appId: '1:848790076272:android:c5a2fb8345e37324192db5',
    messagingSenderId: '848790076272',
    projectId: 'dollar-ac665',
    databaseURL: 'https://dollar-ac665-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dollar-ac665.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpGb21esixzpNjmSjroG6FFTXSlD8QptQ',
    appId: '1:848790076272:ios:77b8435b98bf2395192db5',
    messagingSenderId: '848790076272',
    projectId: 'dollar-ac665',
    databaseURL: 'https://dollar-ac665-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dollar-ac665.firebasestorage.app',
    iosBundleId: 'com.example.mid23141010',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpGb21esixzpNjmSjroG6FFTXSlD8QptQ',
    appId: '1:848790076272:ios:77b8435b98bf2395192db5',
    messagingSenderId: '848790076272',
    projectId: 'dollar-ac665',
    databaseURL: 'https://dollar-ac665-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dollar-ac665.firebasestorage.app',
    iosBundleId: 'com.example.mid23141010',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZL6fUZ6vDylvJnwE1n7TvINblhWO1OPY',
    appId: '1:848790076272:web:41e662b1161605c2192db5',
    messagingSenderId: '848790076272',
    projectId: 'dollar-ac665',
    authDomain: 'dollar-ac665.firebaseapp.com',
    databaseURL: 'https://dollar-ac665-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dollar-ac665.firebasestorage.app',
    measurementId: 'G-1VZ2CXD89Y',
  );
}
